// src/mockData.js

export const drugs = [
  // Non-Prescription Drugs (OTC)
  {
    id: 1,
    drug: "Paracetamol 500mg",
    pharmacy: "HealthPlus",
    price: 150,
    location: "Lagos",
    image: "https://via.placeholder.com/240?text=Paracetamol",
    quantity: 50,
    packSize: "10 tablets",
    phone: "08012345678",
    requiresPrescription: false,
  },
  {
    id: 2,
    drug: "Paracetamol 500mg",
    pharmacy: "GoodHealth",
    price: 140,
    location: "Lagos",
    image: "https://via.placeholder.com/240?text=Paracetamol",
    quantity: 30,
    packSize: "10 tablets",
    phone: "08087654321",
    requiresPrescription: false,
  },
  {
    id: 3,
    drug: "Ibuprofen 400mg",
    pharmacy: "WellCare",
    price: 900,
    location: "Ogun",
    image: "https://via.placeholder.com/240?text=Ibuprofen",
    quantity: 40,
    packSize: "10 tablets",
    phone: "08056789012",
    requiresPrescription: false,
  },
  {
    id: 4,
    drug: "Ibuprofen 400mg",
    pharmacy: "HealthLine",
    price: 850,
    location: "Ogun",
    image: "https://via.placeholder.com/240?text=Ibuprofen",
    quantity: 60,
    packSize: "10 tablets",
    phone: "08067890123",
    requiresPrescription: false,
  },

  // Prescription Drugs (POM / Controlled)
  {
    id: 5,
    drug: "Amoxicillin 500mg",
    pharmacy: "MediCare",
    price: 2200,
    location: "FCT - Abuja",
    image: "https://via.placeholder.com/240?text=Amoxicillin",
    quantity: 10,
    packSize: "10 capsules",
    phone: "08023456789",
    requiresPrescription: true,
  },
  {
    id: 6,
    drug: "Amoxicillin 500mg",
    pharmacy: "PharmaTrust",
    price: 2100,
    location: "FCT - Abuja",
    image: "https://via.placeholder.com/240?text=Amoxicillin",
    quantity: 12,
    packSize: "10 capsules",
    phone: "08034567890",
    requiresPrescription: true,
  },
  {
    id: 7,
    drug: "Metformin 1g",
    pharmacy: "CityPharma",
    price: 2800,
    location: "Lagos",
    image: "https://via.placeholder.com/240?text=Metformin",
    quantity: 8,
    packSize: "30 tablets",
    phone: "08078901234",
    requiresPrescription: true,
  },
  {
    id: 8,
    drug: "Metformin 1g",
    pharmacy: "MediPlus",
    price: 2900,
    location: "Lagos",
    image: "https://via.placeholder.com/240?text=Metformin",
    quantity: 15,
    packSize: "30 tablets",
    phone: "08089012345",
    requiresPrescription: true,
  },
];
